# Nom de l'application, utilisé par Eureka pour l'enregistrement
spring.application.name=mygateway

# Activer la découverte via Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Port par défaut (facultatif, utile pour savoir où l'app tourne)
server.port=8080

# Désactiver le crash si le Config Server n’est pas accessible (optionnel mais conseillé en dev)
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888

# Desactiver la source de donnees de gateway puisque la gateway n'a pas besoin de la base de donnee
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
